# Generated by Django 5.2.4 on 2025-07-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_teacher_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='feedback',
            name='areas_for_improvement',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='feedback',
            name='overall_assessment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='reviewer_type',
            field=models.CharField(choices=[('AI', 'AI Generated'), ('HUMAN', 'Human Reviewer')], default='AI', max_length=10),
        ),
        migrations.AddField(
            model_name='feedback',
            name='strengths',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='feedback',
            name='suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
