# Generated by Django 5.2.4 on 2025-07-10 17:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedback'},
        ),
        migrations.AlterModelOptions(
            name='lessonnote',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Lesson Note', 'verbose_name_plural': 'Lesson Notes'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AddField(
            model_name='feedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lessonnote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='areas_for_improvement',
            field=models.JSONField(blank=True, default=list, help_text='List of areas needing improvement'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='lesson_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_set', to='notes.lessonnote'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='overall_assessment',
            field=models.TextField(blank=True, help_text='Overall assessment summary'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='score',
            field=models.IntegerField(blank=True, help_text='Score from 1-100', null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='strengths',
            field=models.JSONField(blank=True, default=list, help_text='List of strengths identified'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='suggestions',
            field=models.JSONField(blank=True, default=list, help_text='List of suggestions for improvement'),
        ),
        migrations.AlterField(
            model_name='lessonnote',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_notes', to='notes.teacher'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['lesson_note', 'reviewer_type'], name='notes_feedb_lesson__f814e2_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['reviewer_type'], name='notes_feedb_reviewe_68bd12_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['created_at'], name='notes_feedb_created_14fb73_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonnote',
            index=models.Index(fields=['teacher', 'subject'], name='notes_lesso_teacher_fe54ac_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonnote',
            index=models.Index(fields=['status'], name='notes_lesso_status_e24a7d_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonnote',
            index=models.Index(fields=['submitted_at'], name='notes_lesso_submitt_d1cf08_idx'),
        ),
    ]
